---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loadgenerator
  name: loadgenerator
  namespace: easytravel-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
      - env:
        - name: ET_FRONTEND_URL
          value: http://easytravel-prod-nginx-service:80
        - name: ET_BACKEND_URL
          value: http://easytravel-backend-service:8080
        - name: ET_PROBLEMS
          value: DatabaseCleanup
        image: dynatrace/easytravel-loadgen:2.0.0.3256
        name: easytravel-loadgen
